### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by krzysztofstepnikowski** [krzysztofstepnikowski/Xamarin.Forms.EntryAutoComplete#10]
* Default (contains)
* Starts with
* ends with
* custom (IEqualityComparer)

**Comment by krzysztofstepnikowski** [comment]
@brogowski you can do a review and refactor code.

**Comment by brogowski** [comment]
Custom comparer fuctionality is missing.

**Comment by krzysztofstepnikowski** [comment]
Please implement functionality for custom comparer.
