### ISSUE TITLE
MaximumVisibleElements

### ISSUE THREAD

**Issue by krzysztofstepnikowski** [krzysztofstepnikowski/Xamarin.Forms.EntryAutoComplete#11]
Implement set height request listview about how many items contains in the listview.
Implement displaying a count of items in the listview about the set bindable property - MaximymVisibleElements.

Please check this on iOS Platform.

**Comment by brogowski** [comment]
On UWP it's not working - when typing 'b' 11 records are visible.

![image](https://user-images.githubusercontent.com/9166130/46656306-04cb9900-cbae-11e8-9b5b-a1ea610592ff.png)

On iOS it's partially working - only 5 records fits on list but there are several empty records.

![image](https://user-images.githubusercontent.com/9166130/46656259-ecf41500-cbad-11e8-8f64-3901bbee527f.png)
