### ISSUE TITLE
Create simple skeleton

### ISSUE THREAD

**Issue by brogowski** [krzysztofstepnikowski/Xamarin.Forms.EntryAutoComplete#2]
Create iOS & Android app with simple auto complete control.
Let's say it's going to have list of countries - hard coded for now.
Design input box and selectable list of suggestions.

**Comment by krzysztofstepnikowski** [comment]
Android has been done. 
iOS is in progress.

**Comment by krzysztofstepnikowski** [comment]
Done. Control is running on every mobile platform.
