### ISSUE TITLE
Xamarin WPF

### ISSUE THREAD

**Issue by dhpanteon** [krzysztofstepnikowski/Xamarin.Forms.EntryAutoComplete#27]
Is that supports Xamarin WPF?

**Comment by krzysztofstepnikowski** [comment]
Unfortunately, no.

**Comment by dhpanteon** [comment]
Any plan in future to give support for WPF?

**Comment by krzysztofstepnikowski** [comment]
At this moment, I cannot ask you about it, because we have a plan for create something new app. We know that this control is very interested for the developers. If you want, you can extend our project or you can see at Syncfusion.
